### ISSUE TITLE
Fix messages content path at 'admin/content/message'

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#30]
At the moment we have 2 paths for Message Content.
- /admin/content/message
- /admin/content/messages

@RoySegall - as we saw earlier core content paths may not be consistent re: plural vs. singular, e.g. "comment" & "files" in the path.

We need to choose one of these for consistency:
- See singular used in routing yaml and elsewhere.
- See plural in views yaml: 
  "./message/config/optional/views.view.message.yml:495:      path: admin/content/messages"

**Comment by mccrodp** [comment]
See additional more recent info @ https://github.com/Gizra/message/pull/33#issuecomment-143314903

**Comment by mccrodp** [comment]
There is a conflict I believe here between the path defined by the view in _message/config/optional/views.view.message.yml_ and the `message.messages` route in _message.routing.yml_. I think they try to override each other if set to the same value, however currently we have 2 paths: _admin/content/message_ and _admin/content/messages_.

I tried to remove the below, but the MessageViewBuilder / MessageListBuilder are not invoked then, I'm guessing due to the `_entity_list` entry.

```
message.messages:
  path: '/admin/content/messages'
  defaults:
    _title: 'Messages'
    _entity_list: 'message'
  requirements:
    _permission: 'overview messages'
```

I'm not sure how best to solve, perhaps this route can be removed and we modify the route _view.message.page_1_ in a hook in order to invoke the MessageViewBuilder / MessageListBuilder explicitly, but I guess it's better to keep the message.messages route in the yml for clarity.
